var cmentarze_do_1500_roku=
{
"type": "FeatureCollection",
"name": "cmentarze do 1500 roku",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Cmentarz przykościelny par. rzymskokat. pw. św. Andrzeja Apostoła (Spławie)", "ID": "RK45", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/splawie\/", "stan": "relikty", "typ": "rzymskokatolicki", "tekst": "Cmentarz przykościelny istaniał już przy późnośredniowiecznym budynku kościoła, któy został zniszczony w czasie potopu szwedzkiego. Obecna bryła budynku została konsekrowana w 1893 roku. Obecnie zachowane zostały relikty cmentarza przykości", "obecnalok": "ul. Spławie", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.025428, 52.3508645, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przykościelny rzymskokat. par. pw. św. Jakuba Większego Apostoła w Głuszynie", "ID": "RK42", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/gluszyna\/", "stan": "relikty", "typ": "rzymskokatolicki", "tekst": "Cmentarz został założony w średniowieczy i zlokalizowany w jego bezpośredniej bliskości. W XIX wieku przerpowadzone zostały prace renowacyjne polegające na wykonaniu ozdobnych nasadzeń oraz budowei nowego muru zabezpieczającego kościół i ter", "obecnalok": "ul. Głuszyna", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.952063657264599, 52.319105404980014, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przyszpitalny św. Krzyża", "ID": "RK30", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/sw-krzyza\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Cmentarz przy szpitalnu św. Krzyża na przednieściu Półwieś, założony został w XV wieku i funkcjonował prawdopodobnie do XVIII wieku. Chowano na nim ubogich i zniedołężniałych oraz chorych na trąd pacjentów szpitala.", "obecnalok": "ul. Półwiejska", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9312896, 52.4048073, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przyklasztorny karmelitów (Piaski)", "ID": "RK27", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/bozego-ciala\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Cmentarz przyklasztorny zakonu Karmelitów Trzewiczkowych został założony w poźnym sredniowieczu i istaniał do XVIII wieku. Ostatnie relikty cmentarza zostały zlikwidowane w latach 20-tych XX wieku w czasie prowadzenia prac renowacyjnych. W czasie", "obecnalok": "ul. Łąkowa", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9333164, 52.4009958, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przykościelny św. Jana Jerozolimskiego za Murami", "ID": "RK16", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/komandoria\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Cmentarz przykościelny jednej z najwcześniejszych świątyń chrześcijańskich w Poznaniu, funkcjonował już od czasów średniowiecza. Na początku XVIII wieku istniało derwniane ossuarium oraz murowana krypta w ktorej składano szczątki zmarłych", "obecnalok": "ul. Warszawska", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9585815, 52.4096298, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przykościelny św. Małgorzaty", "ID": "RK14", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/komandoria\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Cmentarz przykościelny parafii pw. św. Małgorzaty został założony w średniowieczu, a jego relikty były widoczne jeszcze w XIX wieku. Lokowanie pierwszych miejsc pochówku na Śródce zaczęto w czasach przedchrześcijańskich, a nastpnie w blisko", "obecnalok": "ul. Śródka", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.954081, 52.4112943, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz katedralny ", "ID": "RK13", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/komandoria\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Otoczenie katedry poznańskiej, w szczególności plac przed głównym wejsciem, oraz tereny po północnej i południowej stronie światyni spełniały funkcje cmentarne do okresu późnego średniowiecza. Wyniki badań archeologicznych, ujawniające wi", "obecnalok": "ul. Ostrów Tumski", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9478886, 52.4114213, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przykościelny NMP", "ID": "RK12", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/komandoria\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Niewielki cmentarz zlokalizowany w bezpośrednim sąsiedztwie kościoła NMP na Ostrowie Tumskim istaniał od II połowy XV wieku. Badania archeologiczne świadczą że był użytkowany do XVIII wieku.", "obecnalok": "ul. Ostrów Tumski", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9471278, 52.4109956, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przykościelny św. Wojciecha", "ID": "RK8", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/stary-sw-wojciech\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Cmentarz przykościelny parafii pw. św. Wojciecha, sąsaiadujący z jednym z najstarszych kościołów lewobrzeżnego Poznania. Funkcjonował do przełomu lat 20\/30-tych XIX wieku. Szczatki zmarłych parafian złożone ostatecznie w przykoscielnym ossua", "obecnalok": "ul. Święty Wojciech", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9326341, 52.4134865, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Nowy Cmentarz (parafii farnej) z kolegiatą Wszystkich Świętych", "ID": "RK5", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/fara\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Nowy cmentarz parafii farnej założony został w drugiej dekadzie XV wieku. Nekropolia została zlokalizowana poza obszarem murów miejskich na przedmieściu Piaski. Cmentarz przznaczony był dla uboższej części mieszkańców miasta. Cmentarz został", "obecnalok": "ul. Za Bramką", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9363638, 52.4060146, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz kolegiacki (farny)", "ID": "RK4", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/fara\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Cmentarz przykościelny parafii farnej pw. św. Marii Magdaleny został założony w średniowieczu i działał do II połowy XVIII wieku. W ramach prowadzonychrewitalizacji placu i prowadzonych prac areologicznych (2015-2021) ujawniono pochówki kilku t", "obecnalok": "pl. Kolegiacki", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9356061, 52.406773499999986, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przykościelny św. Marcina", "ID": "RK1", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/staromarcinski\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Cmentarz przykościelny, został założony w średniowieczu i funkcjonowal do końca XVIII wieku. Był wielokrotnie dewastowany w czasie działań wojennych prowadzonych przez Brandenburczyków, Szwedów, Rosjan, Prusaków. Zajmowal obszar do ul. Wysoki", "obecnalok": "ul. Święty Marcin", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9279262, 52.4058093, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przyszpitalny Świętego Ducha", "ID": "RK58", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/sw-ducha\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Cmentarz przy szpitalu Świętego Ducha istniał zapewne od jego załozenia w II połowie XV wieku. Szpital był przeznaczony w szczególności dla porzuconych dzieci i starców. Szpital i współistniejący z nim kościół zostały rozebrane w I połow", "obecnalok": "ul. Wolnica", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.933603, 52.4113207, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przyklasztorny katarzynek", "ID": "RK55", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/katarzynek\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Cmentarz przyklasztorny zakonu Dominikanek założony został w XIII wieku.  W XIV wieku kościół klasztorny zyskał nowe wezwanie św. Katrzyny ze Sieny i w wziązku z tym zakonnice otrzymały przydomek katarzynek. W latach 20-tych XIX wiekunastąpił", "obecnalok": "ul. Masztalarska", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9335408, 52.4104068, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz przyklasztorny dominikanów", "ID": "RK54", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/dominikanow\/", "stan": "zlikwidowany", "typ": "rzymskokatolicki", "tekst": "Cmentarz przyklasztorny zakonu Dominikanów założony został w średniowieczu na terenie osady św. Gotarda. Funkcjonował jeszcsze w XVIII wieku. W ramach prowadzonych w latach 70-tych XX wieku prac archeologicznych ujawione zostały liczne groby i os", "obecnalok": "ul. Garbary", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9378399, 52.4101948, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz par. rzymskokat. pw. Michała Archanioła i Wniebowzięcia Najświętszej Maryi Panny (Kiekrz)", "ID": "RK51", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/kiekrz\/", "stan": "istnieje", "typ": "rzymskokatolicki", "tekst": "Najstarsza część cmentarza parafii pw. Michała Archanioła i Wniebowzięcia Najświętszej Maryi Panny została założona w średniowieczu. Najstarsze zachowane nagrobki pochodzą z II połowy XIX wieku gdy odbudowie uległa znisczona w wyniku poża", "obecnalok": "ul. Chojnicka", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.7848143, 52.4764981, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Stary cmentarz żydowski", "ID": "J4", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/zydowskie\/kirkuty\/", "stan": "zlikwidowany", "typ": "żydowski", "tekst": "Najprawdopodobniej najstarszy cmentarz poznańskiej gminy żydowskiej. Został założony w średniowieczu i istniał do początku XIX wieku. Realizacja nowej koncepcji urbanistycznej i wytycznenie nowej dzielnicy tzw. Górnego Miasta wiązała się z li", "obecnalok": "ul. Feliksa Nowowiejskiego", "do1500": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9262529, 52.4093513, 0.0 ] } }
]
}
