var francuski=
{
"type": "FeatureCollection",
"name": "francuskie",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Mauzoleum żołnierzy francuskich", "ID": "F4", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/garnizonowe\/francuskie\/", "stan": "zlikwidowany", "typ": "francuski", "tekst": "W czasie dwudziestolecia międzywojennego zadecydowano o likwidacji istniejących dotychczas miejsc pochówku żołnierzy francuskich i przeniesieniu ich do zbiorowej mogiły. W ten sposób na skotach Cytadeli we wspólnym grobowcu zostały pochowane szczątki żołnierzy armii napoleońskiej, jeńców wojny francusko-pruskiej zatrudnionych przy budowie poznańskich fortów. Szczątki żołnierzy francuskich i belgijskich walczących w I wojnie światowej zostały w 1923 roku odesłane do ojczyzny.", "obecnalok": "ul. Armii Poznań", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9316775, 52.4188243, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz żołnierzy Napoleona", "ID": "F3", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/garnizonowe\/francuskie\/", "stan": "zlikwidowany", "typ": "francuski", "tekst": "Cmentarz założony w 1807 roku na dużą śmiertelnością żołnierzy armii Napoleona przebywających w Poznaniu. Groby istaniały do porzełomu lat 30/40-tych XIX wieku. Ostatecznie szczątki do krypt klasztoru Reformatorów, skąd zostały wywiezione w okresie II wojny światowej przez niemieckie wojsko.", "obecnalok": "ul. Piotra Tomickiego", "do1500": 0, "od1501do17": 0, "od1772do19": 1, "od1920do19": 0, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9603304, 52.4104152, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz żołnierzy Napoleona", "ID": "F2", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/garnizonowe\/francuskie\/", "stan": "zlikwidowany", "typ": "francuski", "tekst": "Cmentarz istniał w I połowie XIX wieku i był miejscem spoczynku żołnierzy armii Napoleona, którzy umarli w szpitalach wojskowych.", "obecnalok": "ul. Strzelecka", "do1500": 0, "od1501do17": 0, "od1772do19": 1, "od1920do19": 0, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9339928, 52.401648199999975, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera jeńców francuskich 1870-1871", "ID": "F1", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/garnizonowe\/francuskie\/", "stan": "zlikwidowany", "typ": "francuski", "tekst": "Kwatera żołnierzy francuskich wojny prusko-francuskiej 1870-1871 istaniała w ramach ramach cmentarza ewangelickiego parafii św. Pawła. Pochowani w niej zostali jeńcy zmarli na tyfus i dyzenterię. Ekschumacje prowadzone w ramach przeniesienia szczątków do mauzoleum na Cytadeli, ujawniły zbiorowe mogiły nie posiadające oznaczeń naziemnych.", "obecnalok": "ul. Mieczysława Niedziałkowskiego", "do1500": 0, "od1501do17": 0, "od1772do19": 1, "od1920do19": 1, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9253617, 52.3996579, 0.0 ] } }
]
}
