var komunalny=
{
"type": "FeatureCollection",
"name": "komunalne",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Cmentarz Komunalny nr 2 w Poznaniu (Junikowo)", "ID": "K2", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/junikowo2\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Prace koncepcyjne nad założeniem wielowyznaniowego cmentarza miejskiego prowadzone były w latach 1927-1935. Szczegółowego projektu nekropolii nie zrezalizowano w okresie międzywojennym. Do realizacji tych planów powrócono po zakończeniu II wojny światowej. Zgodnie z nimi na terenie Poznania mialy powstać cztery główne nekropolie: Miłostowo, Minikowo, Junikowo i Golęcin. W latach 1947-1950 zrealizowano projekt cmentarza Junikowo i dokończono Miłostowo. W latach 70-tych obszar cmentarza został powiększony o sąsiadujący z nim las, zwiększając powierzchnie do 90 ha.", "obecnalok": "ul. Cmentarna", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.8326756, 52.386255, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz Komunalny nr 1 w Poznaniu (Miłostowo)", "ID": "K1", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Pierwotnie nazywany cmentarzem na Głównej. Został założony podczas niemieckiej okupacji jako główny miejski cmentarz. Został zbudowany w oparciu o niewolniczą pracę Żydów i Polaków. W chwili jego otwarcia w 1943 roku, zamknięto jednocześnie dla pochówków dwa czynne w czasie okupacji cmentarze parafialne. Po wojnie kontułllowano prace nad urządzeniem terenu poprzez wykonywanie nasadzeń mających wzmocnić strukturę piaszczystego grunut. W wyniku tej działalności na początku lat 50-tych XX wieku zalesiono teren calego cmentarza. Według powowjonenych założeń nerpolia miała stać się jednym z czterech głównych cmentarzy na terenie Poznania. Na teren cmentarza przenoszone były szczątki z cmantarzy ewangelickich likwidowanych po II wojnie światowej, tworząc kwatery: żegierską, maltańską i świetowojciechową. Na cmentarzu wyznaczono wyodrebnione miejsca dla lotników, kombatantów, żołnierzy polskich, radzieckich oraz niemieckich, muzułmanów, prawosławnych i świadków Jehowy. W 1993 roku w Forcie IIIa założone zostało pierwsze w Polsce krematorium.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0035774, 52.4136287, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera maltańska", "ID": "K10", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/malta\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Miejsce powtórnego pochówku szczątków ekshumowanych z cmentarzy znajdujących się na Malcie.Kwatera została utworzona na przełomie lat 40/50-tych XX wieku. Na trerenie kwatery przewżają bezimienne nagrobki ziemne. Część z ponowych pochówków została w latach 70-tych powtórnie ekshumowana i przeniesiona do innych kwater na cmentarzu Miłostowo.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0074764, 52.4173082, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Pole urnowe oraz kolumbarium", "ID": "K11", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/kremacje\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Pole urnowe i kolumbarium zostało założone w 1993 roku, w związku z uruchomieniem pierwszego w Polsce zakładu kremacji zwłok.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0010411, 52.4159012, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Groby ofiar nalotów z 1 września 1939 r.", "ID": "K15", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/kwatera-ofiar-bombardowan-1939\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Kwatera została utworzona w 1961 roku. Przeniesiono w to miejsce ofiary nalotów bombowych z 1 września 1939 roku, pochowane pierowtnie na cmentarzu staromarcińskim przy ul. Towarowej. W grudniu 2019 roku, do kwatery przeniesiono szczątki ofiar bombardowań, które pierwotnie zostały pochowane na cmentarzu przy ulicy Samotnej.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0050879, 52.4146417, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Krzyż żegierski", "ID": "K16", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/wiatraczna\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Kwatera do której przeniesione zostały w latach 70-tych XX wieku pochówki z likwidowanego cmentarza żegierskiego. Prace ekhumacujne na likwidowanym cmentarzu zostały przeprowaadzone tylko częściowo.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0038466, 52.421097399999979, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Zbiorowa mogiła ekshumowanych z cmentarza staromarcińskiego", "ID": "K17", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/staromarcinski\/", "stan": "istnieje", "typ": "komunalny", "tekst": "W zbiorowym grobie znajdują się pochówki z likwidowanego w latach 50\/60-tych cmentarza staromarcińskiego.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9949882, 52.4189081, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Groby cywilnych ofiar nalotów alianckich w 1944 r.", "ID": "K18", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/kwatera-ofiar-bombardowan-1944\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Kwatera z grobami cywilnych ofiar nalotów alianckich na Poznań w 1944 roku.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9975547, 52.4242482, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Zbiorowa mogiła ekshumowanych z nowego cmentarza świętokrzyskiego", "ID": "K19", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/ewangelickie\/schillingfriedhof\/", "stan": "istnieje", "typ": "komunalny", "tekst": "W zbiorowym grobie znajdują się pochówki z likwidowanego w latach 60-tych XX wieku cmentarza świętokrzyskiego.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0045177, 52.4148366, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Zbiorowa mogiła ekshumowanych ze starego cmentarza św. Pawła", "ID": "K20", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/ewangelickie\/stpaulifriedhof\/", "stan": "istnieje", "typ": "komunalny", "tekst": "W zbiorowym grobie znajdują się szczątki ze zlikwidowanego w latach 50-tych XX starego cmentarza ewangelickiego parafii św. Pawła. W czasie likwidacji pierwotnego cmentarza nie przeprowadzono prac ekshumacyjnych. Szczątki (w tym ossuarium) zostały ujawnione w czasie prac rewitalizacyjnych w latach  2019-2020.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0045944, 52.4148494, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Zbiorowa mogiła ekshumowanych z Nowego Cmentarza (farnego)", "ID": "K21", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/mtp\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Zbiorowa mogiła zawierająca szczątki przeniesione w latach 40-tych XX z likwidowanego cmentarza nowofarnego.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9951303, 52.4187715, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Zbiorowa mogiła ekshumowanych z cmentarza winogradzkiego", "ID": "K22", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/rzymskokatolickie\/winogradzki\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Zbiorowa mogiła zawierająca szczątki przeniesione w latach 70-tych XX z likwidowanego cmentarza winogradzkiego", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0061607, 52.4198145, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz muzułmański", "ID": "K23", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/kwatera-muzulmanska\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Teren cmentarza został wydzielony na prośbę gminy muzułmańskiej w 2006 roku.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0033655, 52.4151712, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera ewangelicka", "ID": "K24", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/kwatera-ewangelicka\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Utworzona w 1943 roku. Regularne pochówki zaczęły się w I połowie 1945 roku. W kolejnych latach, przenoszone były w to miejsce szczątki z likwidowanych cmentarzy ewangelickich na terenie miasta m.in. z górczyńskiego cmentarza Chrystusa.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.004143, 52.414883, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera prawosławna", "ID": "K25", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/kwatera-prawoslawna\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Kwatera została utworzona w 1943 roku i jest nadal użtkowana przez parafię prawosławną św. Mikołaja w Poznaniu.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0038982, 52.4153723, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera duchowieństwa", "ID": "K26", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/duchowienstwo\/", "stan": "istnieje", "typ": "komunalny", "tekst": "W kwaterze duchowieństwa spoczywają siostry: elżbietanki, serafitki, szarytki i franciszkanki oraz ojcowie jezuici i chrystusowcy. Chowani są również proboszczowie poznańskich parafii. Wpołowie lat 60-tych XX wieku przesione zostały na to miejsce szczątki kanoników Kapituły Metropolitalnej z likwidowanych cmentarzy na Komandorii.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.998057433894825, 52.423764320547029, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera lotników", "ID": "K27", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/kwatera-lotnikow-pl\/", "stan": "istnieje", "typ": "komunalny", "tekst": "W 1997 roku odsłonięty został pomnik poświęcony Polskim Lotnikom 1918-1939-1945. W kolumbarium zostały złożona ziemia z cmentarzy wojennych i pól bitewnych z lat 1918-1920 (Poznań-Ławica, Lwów, Warszawa) i 1939-1945 (Dęblin, Kołobrzeg, Kraków, Łódź, Piła, Poznań, Radomsko, Wałcz, Warka, Warszawa, Wieluń, Francja, Anglia, Afryka Północna).", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0079871, 52.412854699999983, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Obelisk w Kwaterze Kombatantów", "ID": "K28", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/kombatanci\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Kwatera Kombatantów została założona w 1999 roku i jest poświęcona walczącycm o niepodległość Polski w latach 1918-1956.", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0057024, 52.4132706, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera żołnierzy Armii Krajowej", "ID": "K31", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/junikowo2\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Groby żołnierzy Armii Krajowej", "obecnalok": "ul. Cmentarna", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.835038584588577, 52.384642442710714, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera Powstańców Wielkopolskich 1918-1919", "ID": "K32", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/junikowo2\/powstancy-wielkopolscy-1918-1919\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Kwatera została utworzona w latach 80-tych XX wieku i zawiera groby uczestników Powstania Wielkopolskiego 1918-1919.", "obecnalok": "ul. Cmentarna", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.836760897092756, 52.384843890350076, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera Kombatancka 1939-1956", "ID": "K33", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/junikowo2\/", "stan": "istnieje", "typ": "komunalny", "tekst": "Groby uczestników walk o niepodległość Polski z lat 1939-1956.", "obecnalok": "ul. Cmentarna", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.828503680903051, 52.389301099983491, 0.0 ] } }
]
}
