var prawosławny=
{
"type": "FeatureCollection",
"name": "prawosławne",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Prawosławny Cmentarz Garnizonowy (św. Mikołaja)", "ID": "PR4", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/garnizonowe\/sw-mikolaj\/", "stan": "relikty", "typ": "prawosławny", "tekst": "Prawosławny cmentarz garnizonowy został założony wkrótce po ustanowieniu w 1924 roku prawosławnej prafaii św. Mikołaja. Działalność parafii skierowana była przede wszyskim na przesiedleńców i rekrutów z Kresów Wschodnich, którzy odbywali służbę w poznańskim garnizonie. Wśród wiernych parafii znajdowali się również jeńcy rosyjscy z okresu I wojny światowej i Biali Rosjanie walczący z rewolucją bolszewicką. Wiekszość nagrobków została zniszczona w czasie walk o Poznań w lutym 1945 roku. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Armii Poznań", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9333729, 52.4183127, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz grecki przy ul. Towarowej", "ID": "PR3", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/prawoslawne\/dyzunickie\/", "stan": "zlikwidowany", "typ": "prawosławny", "tekst": "Cmentarz prawosławny disapory greckiej założony w połowie lat 50-tych XIX wieku. Tutaj przeniesione zostały pochówki z likwidowanego starego cmentarza greckiego. W 1884 roku administrację cmentarza przejeła parafia św. Marcina, która została zobowiązana do zachowania pierwotnych nagrobków. Cmentarz, bez przeprowadzenia prac ekshumacyjnych, został ostatecznie zlikwidowany na przełomie lat 50/60-tych XX wieku. Wybrane pochówki przeniesione zostały na Cmentarz Zasłużonych Wielkpololan. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Towarowa", "do1500": 0, "od1501do17": 0, "od1772do19": 1, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9169989, 52.4048177, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "„Stary cmentarz” diaspory greckiej", "ID": "PR2", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/prawoslawne\/dyzunickie\/", "stan": "zlikwidowany", "typ": "prawosławny", "tekst": "Cmenatrz prawosławny diaspory greckiej założony w połowie lat 90-tych XVIII wieku. Został zlikwidowany w połowie XIX wieku wskutek rozbudowy twierdzy poznańskiej. Ekshumowane szczątki przeniesione zostały na nowy cmentarz grecki przy ul. Towarowej. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Przemysłowa", "do1500": 0, "od1501do17": 0, "od1772do19": 1, "od1920do19": 0, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9179833, 52.4002325, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz diaspory greckiej na przedmieściu Nowe Ogrody\/św. Marcin", "ID": "PR1", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/prawoslawne\/dyzunickie\/", "stan": "zlikwidowany", "typ": "prawosławny", "tekst": "Jest to najstarszy cmentarz prawosławny dispory  greckiej. Jej przedstawiciele osiedlili się w Poznaniu w II połowie XVIII wieku. Cmentarz zlokalizowny był za bramą wrocławską, po południowej stronie dzisiejszej ul. św. Marcin. Swoją funkcję poełnił do lat 90-tych XVIII wieku. W 1788 roku doszło do profanacji grobów, dokonanej przez polskich kupców. Dokładna lokalizacja cmentarza nie jest znana. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Piekary", "do1500": 0, "od1501do17": 1, "od1772do19": 0, "od1920do19": 0, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9274081, 52.405023599999986, 0.0 ] } }
]
}
