var wojskowy=
{
"type": "FeatureCollection",
"name": "wojskowe",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Cmentarz Bohaterów Polskich", "ID": "K7", "link": "https:\/\/www.poznan.pl\/mim\/wortals\/cmentarze\/cmentarz-bohaterow-polskich,p,1943,15548,15933.html", "stan": "istnieje", "typ": "wojskowy", "tekst": "Cmentarz Boohaterów został założony w listopadzie 1945 roku. Znalazły się na nim groby żołnierzy radzieckich oraz Cytadelowców biorących udział w walkach o Fort Winiary. Obecnie na jego obszarze znajdują się groby ofiar: Poznańskiego Czerwca 1956 roku, nalotów z września 1939 roku, oraz liczne groby symboliczne ze szczątkami pochodzącymi z miejsc kaźni Polaków: z obozu w Żabikowie, Domu Żołnierza, więzienia na Młynskiej, Fortu V i Fortu VII, Lasów Rożnowskich i Palędzkich. Upamiętniono również ofiary powojennego terroru stalinowskiego oraz ich katów. Cmentarz Bohaterów Polskich pokazuje trudną historię narodu Polskiego po 1939 roku. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Armii Poznań", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9328226, 52.4183191, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz Bohaterów Radzieckich", "ID": "K6", "link": "https:\/\/www.poznan.pl\/mim\/wortals\/cmentarze\/cmentarz-bohaterow-radzieckich,p,1943,15548,23941.html", "stan": "istnieje", "typ": "wojskowy", "tekst": "Cmentarz został założony w 1945 roku w miejscu istniejącego wcześniej starego pruskiego cmentarza garnizonowego. Pochowano na nim żołnierzy radzieckich. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Armii Poznań", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9308328, 52.41898650000001, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz Wojenny Wspólnoty Brytyjskiej (Poznan Old Garrison Cemetery)", "ID": "K5", "link": "https:\/\/www.poznan.pl\/mim\/wortals\/cmentarze\/cmentarz-wojenny-wspolnoty-brytyjskiej,p,1943,15548,15549.html", "stan": "istnieje", "typ": "wojskowy", "tekst": "Jest to najstarszy cmentarz w Polsce podlegly Komisji Grobów Wojennych Wspólnoty Narodów. Został założony w 1925 roku na gruntach starego pruskiego cmentarza garnizonowego. Cmentarz uległ został znacznej dewastacji w czasie walk o Fort Winiary w lutym 1945 roku. Prace renowacyjne były prowadzone w latach 1955 oraz 2004. Podobnie jak wszystkie cmentarze wojenne Wspólnoty Brytyjskiej, ten również zrealizowany jest w jednolitej estetyce (Krzyż Ofiarności oraz pionowe kamienne stelle). [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Armii Poznań", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9330403, 52.4178645, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz Garnizonowy (polski)", "ID": "K4", "link": "https:\/\/www.poznan.pl\/mim\/wortals\/cmentarze\/cmentarz-garnizonowy,p,1943,15548,15550.html", "stan": "relikty", "typ": "wojskowy", "tekst": "Najstarsze pochówki nowego (polskiego) cmentarza garnizonowego pochodzą z czasu powstania wielkopolskiego oraz walk o ksztalt granic II Rzeczypospolitej. Obecna forma została nadana w latach 60 i 70-tych XX wieku. W okresie międzywojennym na cmentarzu chowani byli członkowie poznańskiego granizonu i ich rodziny. Osobna kwatera została wydzielona dla lotników wojskowych z Ławicy. Cmentarz uległ znacznej dewastacji w czasie walk o Fort Winiary w lutym 1945 roku. Zaginęły rownież księgi cmentarne, uniemożliwiając obecnie ustalenie personaliów osób tam pogrzebanych. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Armii Poznań", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9266673, 52.4208382, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Dawny cmentarz starogarnizonowy (pruski)", "ID": "K3", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/garnizonowe\/garnisonkirchhof\/", "stan": "relikty", "typ": "wojskowy", "tekst": "Cmentarz został założony na przełomie lat 30/40-tych XIX wieku. Został zniszczony podczas walk o Fort Winiary w lutym 1945 roku. Istnieją jednak relikty takie jak zachowany układ alejek, nagrobki i obeliski. Jednak większość terenu cmentarza zajmują groby wojenne żołnierzy radzieckich. Pierwotnie pochówki na pruskim cmentarzu były wielonarodowe i wielowyznaniowe. Częścią pruskiego cmentarza garnizonowego był Cmentarz honorowy z okresu I wojny światowej. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Armii Poznań", "do1500": 0, "od1501do17": 0, "od1772do19": 1, "od1920do19": 1, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9298409, 52.419100799999988, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Cmentarz 6. Pułku Grenadierów", "ID": "FP8", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/garnizonowe\/grenadier-reg6\/", "stan": "zlikwidowany", "typ": "wojskowy", "tekst": "Prawdopodny cmentarz  w sąsiedztwie koszar 6 Pułku Grenadierów. Poza pruską mapą topograficzną Messtischblatt z lat 80-tych XIX wieku, brak innych źródeł potwierdzających jego istnienie. Poźniejsze edycje mapy topograficznej powierdzają wyłącznie istnienie pomnika. W 1899 roku został odsłonięty pomnik poświęcony pamięci 6 Pułku Grenadierów poległych w wojnach 1866 i 1870-1871. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Szylinga", "do1500": 0, "od1501do17": 0, "od1772do19": 1, "od1920do19": 0, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9013587, 52.4066865, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Tymczasowy Cmentarz Bohaterów", "ID": "FP7", "link": "https:\/\/www.poznan.pl\/mim\/wortals\/cmentarze\/cmentarz-bohaterow-radzieckich,p,1943,15548,23941.html", "stan": "zlikwidowany", "typ": "wojskowy", "tekst": "Tymczasowy cmentarz założony na przełomie lutego i marca 1945 roku po zakończeniu walk o Poznań. Pochowano na nim Cytadelowców, ofiary terrou hitlerowskiego oraz oficerów Armii Czerwonej. Tymczasowe nagrobki pozyskiwane były z pobliskich cmentarzy ewangelickich. Cmentarz został zlikwidowany jesienią 1945 roku, a pochówki przeniesiono na Cmentarz Bohaterów Radzieckich. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Święty Marcin", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9169915, 52.4078264, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera żołnierzy polskich", "ID": "K12", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/kwatera-zolnierzy-pl\/", "stan": "istnieje", "typ": "wojskowy", "tekst": "Kwatera utworzona w 1945 roku, na potrzeby pochówków żołnierzy Ludowego Wojska Polskiego , uczestników Operacji berlińskiej. Po zakończeniu II Wojny Światowej, miejsce służy pochówkom kombatantów LWP. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0039167, 52.414392, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera żołnierzy radzieckich", "ID": "K13", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/rus\/", "stan": "istnieje", "typ": "wojskowy", "tekst": "Kwatera żołnierzy Armii Czerwonej utworzona w 1945 roku. Powstała w wyniku likwiadacji tymczasowych grobów wojennych żołnierzy zmarłych w lazaretach i podczas kampanii prowadzonej na terenie Wielkopolski. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.007352, 52.4140637, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kwatera żołnierzy niemieckich", "ID": "K14", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/komunalne\/milostowo\/ger\/", "stan": "istnieje", "typ": "wojskowy", "tekst": "Kwatera wojenna żołnierzy niemieckich utworzona została w 1943 roku. Wykorzystywana na powtórne pochówki szczątków żołnierzy niemieckich, ujawnianych podczas powojennej akcji komasacyjnej. Obecnie organizowane są zbiorowe pochówki szczątków żołnierzy niemieckich ujawnianych na terenie Wielkopolski w ramach działań Pracowani Badań Historycznych i Archeologicznych Pomost. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 1, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0070744, 52.4155112, 0.0 ] } }
]
}
