var zydowski=
{
"type": "FeatureCollection",
"name": "zydowskie",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Cmentarz żydowski", "ID": "J5", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/zydowskie\/kirkuty\/", "stan": "zlikwidowany", "typ": "żydowski", "tekst": "Cmentarz żydowski założony na początku XIX wieku, funkcjonował również w okresie międzywojennym. Został zlikwidowany w czasie okupcji niemieckiej. Rozbite macewy pochodzące z tego cmentarza, administracja okupacyjna wykorzystywała do budowy dróg, umocnień brzegów rzeki Bogdanka, oraz bydowy sztucznego jeziora Rusałka. Szczątki ujawniane w czasie prac budowlanych prowadzonych na terenach targowych po II wojnie światowej, przenoszono do kwatery żydowskiej na Miłostowie. W 2008 roku na ocalałej części cmentarza założone zostało lapidarium. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Głogowska", "do1500": 0, "od1501do17": 0, "od1772do19": 1, "od1920do19": 1, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9053657, 52.4014722, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Stary cmentarz żydowski", "ID": "J4", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/zydowskie\/kirkuty\/", "stan": "zlikwidowany", "typ": "żydowski", "tekst": "Najprawdopodobniej najstarszy cmentarz poznańskiej gminy żydowskiej. Został założony w średniowieczu i istniał do początku XIX wieku. Realizacja nowej koncepcji urbanistycznej i wytycznenie nowej dzielnicy tzw. Górnego Miasta wiązała się z likwidacją nekropolii. Pomimo rygorystycznemu prawu halachicznemu część pochówków została przeniesiona na nowy cmentarz żydowski przy ul. Głogowskiej (obecnie teren targowe MTP). [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Feliksa Nowowiejskiego", "do1500": 1, "od1501do17": 1, "od1772do19": 1, "od1920do19": 0, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.9262529, 52.4093513, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Lapidarium i kwatera żydowska", "ID": "J3", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/zydowskie\/kirkuty\/", "stan": "relikty", "typ": "żydowski", "tekst": "Kwatera żydowska założona w 1958 roku na cmentarzu miłostowskim. Od 1993 roku ma charakter kirkutu. Pochowane zostały na niej szczątki Żydów zamordowanych w czasie okupacji hitlerowskiej oraz pochodzące ze zlikwidowanych w czasie II wojny światwowej cmentarzy. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Kępa", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 17.0046654, 52.412331499999986, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Nowy cmentarz żydowski", "ID": "J2", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/zydowskie\/kirkuty\/", "stan": "zlikwidowany", "typ": "żydowski", "tekst": "Cmentarz żydowski założony przed I wojną światową, ostatnie pochówki pochodzą z końca lat 30-tych XX wieku. Nekropolia zaprojektowana była na około 7 tysięcy grobów. Cmentarz zlikiwdowany w okresie powojennym. Obecnie teren zarządzny jest przez ROD Jutrzenka. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Wawrzyńca Engestroma", "do1500": 0, "od1501do17": 0, "od1772do19": 1, "od1920do19": 1, "od1946doob": 0 }, "geometry": { "type": "Point", "coordinates": [ 16.888929, 52.4146965, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Lapidarium żydowskie", "ID": "J1", "link": "https:\/\/e-lapidarium.pl\/cmentarze\/zydowskie\/kirkuty\/", "stan": "relikty", "typ": "żydowski", "tekst": "Lapidarium utworzone w 2008 roku na ocalałym fragmencie cmentarza żydowskiego założonego na początku XIX wieku. Odtworzono na nim groby wybitnego talmudysty, rabina Akivy Egera i jego rodziny. [opracowano na podstawie strony: e-lapidarium.pl]", "obecnalok": "ul. Głogowska", "do1500": 0, "od1501do17": 0, "od1772do19": 0, "od1920do19": 0, "od1946doob": 1 }, "geometry": { "type": "Point", "coordinates": [ 16.9049892, 52.4001179, 0.0 ] } }
]
}
